name: DevOps Site CI/CD
on: 
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t devops-static-site:test .
      - name: Tag Docker image
        run: docker tag devops-static-site:test ghcr.io/rsidhu-dataeko/devops-static-site:${{ github.sha }}
      - name: Push Docker image
        run: docker push ghcr.io/rsidhu-dataeko/devops-static-site:${{ github.sha }}
